export const environment = {
  production: false,

  //Live 
  // BizApiUrl: "https://app9.icicilombard.com/ilservices/motor/v1/",
  // BizTokenURL: "https://ipartner.icicilombard.com/mobileagentapi/api/",
  // apiUrl: "https://ipartner.icicilombard.com/mobileagentapi/api/",
  // RazorPayUrl: "https://ipartner.icicilombard.com/mobileagentapi/",
  // ZDPlanName:"ZD",
  // BasicAuth: "Basic SU0tNzU2NTIxOmxvbWJhcmQxMjM=",
  // GPAAPIUrl:"https://app9.icicilombard.com/ILservices/Misc/v1/",  //"Basic SU0tNTQ2NDM4OkxvbWJhcmQyMDE4",
  // APBpdf: 'https://app9.icicilombard.com/ilservices/misc/v2/',

  // Live in used A
  BizApiUrl: "https://app9.icicilombard.com/ilservices/home/v1/",
  BizTokenURL: "https://bancassurance.icicilombard.com/bancakrgapi/api/",
  apiUrl: "https://bancassurance.icicilombard.com/bancakrgapi/api/",
  RazorPayUrl: "https://bancassurance.icicilombard.com/bancakrgapi/",
  KYCEnv : "production",
  //BasicAuth: "Basic SU0tNzU2NTIxOmxvbWJhcmQxMjM=",  //"Basic SU0tNTQ2NDM4OkxvbWJhcmQyMDE4",
  BasicAuth: "Basic SU0tNDYyMzY6TG9tYmFyZEAzMjE=",
  ZDPlanName: "ZD",
  GPAAPIUrl: "https://app9.icicilombard.com/ilservices/misc/v1/",
  //GPAdealId:"DL-4005/M/4598656",
  GPAdealId: "DL-4186/16114582",
  GPABBGDealId: "DL-4186/17622745",
  GPASMEDealId: "DL-4186/16114582",
  bankName: "Axis",
  commonadppaymentlink: "http://localhost:1200/#/commonadppayment?PolicyId={PolicyId}",
  APBpdf: 'https://app9.icicilombard.com/ilservices/misc/v2/',
  Homelink: "https://bancassurance.icicilombard.com/bancakrgapi/bancakrgmsite/AXISADP/AXISCommonQR/#/product",

//   //Sanityng A
  // BizApiUrl: "https://ilesbsanity.insurancearticlez.com/ilservices/home/v1/",
  // BizTokenURL: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/api/",
  // apiUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/api/",
  // RazorPayUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/",
  // KYCEnv : "uat",
  // //BasicAuth: "Basic SU0tNzU2NTIxOmxvbWJhcmQxMjM=",  //"Basic SU0tNTQ2NDM4OkxvbWJhcmQyMDE4",
  // BasicAuth: "/sjTwiwAIUrUSv2gFp80lg==",
  // ZDPlanName: "ZD",
  // GPAAPIUrl: "https://ilesbsanity.insurancearticlez.com/ilservices/home/v1/",
  // //GPAdealId:"DL-4005/M/4598656",
  // GPAdealId: "DL-4186/16114582",
  // GPABBGDealId: "DL-4186/17622745",
  // GPASMEDealId: "DL-4186/16114582",
  // bankName: "Axis",
  // commonadppaymentlink: "http://localhost:1200/#/commonadppayment?PolicyId={PolicyId}",
  // APBpdf: 'https://ilesbsanity.insurancearticlez.com/ilservices/misc/v2/',
  // Homelink:"https://cldilbancaapp01.insurancearticlez.com/BancaKRGMsite/AxisADP/AXISCommonQR/#/",

  //Sanity in used
  // BizApiUrl: "https://ilesbsanity.insurancearticlez.com/ilservices/home/v1/",
  // BizTokenURL: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/api/",
  // ZDPlanName: "Zero Depreciation",
  // apiUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/api/",
  // RazorPayUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapi/",
  // BasicAuth: "/sjTwiwAIUrUSv2gFp80lg==",
  // GPAAPIUrl:"https://cldilbizapp02.cloudapp.net:9001/ILServices/Misc/v1/",
  // GPAdealId:"DL-4186/1365825",
  // //bankName: "Axis",
  // Homelink:"https://bancassurance.icicilombard.com/bancakrgapi/bancakrgmsite/AXISADP/AXISCommonQR/#/product",
  // KYCEnv : "uat",
  // APBpdf: 'https://ilesbsanity.insurancearticlez.com/ilservices/misc/v2/',

  // UAT in used
  // BizApiUrl: "https://ilesbsanity.insurancearticlez.com/ILservices/Health/v1/",
  // BizTokenURL: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapiUAT/api/",
  // PaymentURL: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapiUAT/api/",
  // apiUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapiUAT/api/",
  // RazorPayUrl: "https://cldilbancaapp01.insurancearticlez.com/bancakrgapiUAT/",
  // ZDPlanName: "Zero Depreciation",
  // GPAAPIUrl: "https://ilesb01.insurancearticlez.com/ilservices/misc/v1/",
  // BasicAuth: "Basic SU0tNDYyMzY6TG9tYmFyZEAxMjM=",
  // GPAdealId: "DL-4186/1365825",
  // GPABBGDealId: "DL-4186/1365825",
  // GPASMEDealId: "DL-4186/1365825",
  // bankName: "Axis",

  LinkSendingMaxLimit: 4,
  LinkWaitTime: 300000,

  //AWS UAT
  // BizApiUrl: "https://cldilbizapp02.cloudapp.net:9001/ILServices/Motor/v1/",
  // BizTokenURL: "https://cldilmobilapp01.insurancearticlez.com/MobileAPI/api/",
  // ZDPlanName:"Zero Depreciation",
  // apiUrl: "https://cldilmobilapp01.insurancearticlez.com/MobileAPI/api/",
  // RazorPayUrl: "https://cldilmobilapp01.insurancearticlez.com/MobileAPI/",
  // BasicAuth: "Basic SU0tNDYyMzY6TG9tYmFyZEAxMjM=",
  //homepage: "http://localhost:4200/#/dashboard",
  TwoWheelerDealId: "DL-3005/2102012",
  FourWheelerDealId: "DL-3001/2084941",

  EncryptedDeal: "Nmg+U/TpIoTNgVFJbJg88A==",
  IMobileTWdeal: "DL-3005/3956980",
  IMobileFWdeal: "DL-3001/3956984",

  // HomeBancaIPaddress: "IBANK",
  IMobileIPaddress: "IMOBILE",
  HomeBancaIPaddress: "AXIS_ONE_QR",
  // HomeBancaGPAIPadress:"RR_GPA",
  BulkBancaIPaddress: "BANCA-UPLOAD",

};